ALTER TABLE drivers ALTER COLUMN state SET NOT NULL;
ALTER TABLE drivers ALTER COLUMN age SET NOT NULL;
ALTER TABLE drivers ALTER COLUMN complexion SET NOT NULL;
ALTER TABLE drivers ALTER COLUMN height SET NOT NULL;
ALTER TABLE drivers ALTER COLUMN license_number SET NOT NULL;
ALTER TABLE drivers ALTER COLUMN license_expiry_date SET NOT NULL;
ALTER TABLE drivers ALTER COLUMN years_of_experience SET NOT NULL;
ALTER TABLE drivers ALTER COLUMN nationality SET NOT NULL;